name: Windows MSVC Build and Test

on:
  push:
    branches:
      - v1.x
  pull_request:
    branches:
      - v1.x

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        msvc_version:
          - { name: "Visual Studio 15 2017", generator: "Visual Studio 15 2017" }
          - { name: "Visual Studio 16 2019", generator: "Visual Studio 16 2019" }
          - { name: "Visual Studio 17 2022", generator: "Visual Studio 17 2022" }

    name: "Windows ${{ matrix.msvc_version.name }} (C++11, Release)"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' --no-progress

      - name: Verify CMake Version
        run: cmake --version

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "${{ matrix.msvc_version.generator }}" -A x64 
            -DCMAKE_BUILD_TYPE=Release 
            -DCMAKE_CXX_STANDARD=11 
            -DSPDLOG_BUILD_EXAMPLE=ON 
            -DSPDLOG_BUILD_EXAMPLE_HO=ON 
            -DSPDLOG_BUILD_WARNINGS=ON 
            -DSPDLOG_BUILD_BENCH=OFF 
            -DSPDLOG_BUILD_TESTS=ON 
            -DSPDLOG_BUILD_TESTS_HO=OFF 
            -DSPDLOG_SANITIZE_ADDRESS=OFF

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build -C Release --output-on-failure --verbose
